[package]
name = "aptos_commission"
version = "1.0.0"
authors = []

[addresses]
aptos_commission = "0x872cc8396366c8b68a2289994b7871aafa9119fab87a0a701e129017dedae835"
reserve_addr = "0x62abdb14a6e0870a79e530abc7d0505a91c26657ccca849a742c236f8d8b3607"
admin_addr = "0x9b2916b5f46b5600d72c3a32624794d05bbad5e50de62853baeaad97887c386d"

[dev-addresses]

[dependencies-remote.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]

[dependencies]
AptosFramework = { local = "./deps/aptosframework/aptos-framework" }
